project:
  type: book
  resources: 
    - ".ttp"

book:
  title: "Atelier Tropy"
  subtitle: "dans le cadre des jeudis d'ITEM"
  author: 
    - "Mélanie Le Couédic"
    - "Julien Rabaud"
  date: "2024-05-16"
  page-navigation: false
  repo-url: https://github.com/ujubib/Quarto_Atelier_Tropy
  repo-subdir: /AtelierTropy/
  repo-actions: [source, issue]
  downloads: [pdf, epub]
  page-footer:
    background: FloralWhite
  sidebar:
    style: "floating"
    background: FloralWhite
    collapse-level: 1
  chapters:
    - index.qmd
    - part: Ressources-tropy.qmd
      chapters:
      - tropy-officiel.qmd
      - tropy-extensions.qmd
      - tropy-tutos.qmd
      - tropy-videos.qmd
      - tropy-blogs.qmd
    - part: Prise-en-main.qmd
      chapters: 
        - tropy-projet.qmd
        - tropy-modeles.qmd
        - tropy-import.qmd
        - tropy-export.qmd
    - FAIR.qmd
    - IIIF.qmd

bibliography: references.bib

format:
  html:
    theme: journal
    lang: fr
    backgroundcolor: FloralWhite
    css: styles.css
    lightbox: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    reference-location: margin
  pdf:
    lang: fr
    documentclass: scrreprt
    reference-location: margin
    links-as-notes: true
  epub: 
    epub-cover-image: cover.png
    lang: fr
    reference-location: margin



