project:
  type: book

book:
  title: "Atelier Tropy"
  subtitle: "dans le cadre des jeudis d'ITEM"
  author: 
    - Mélanie Le Couédic
    - "Julien Rabaud"
  date: "2024-05-16"
  page-navigation: true
  repo-url: https://github.com/ujubib/Quarto_Atelier_Tropy
  repo-subdir: /AtelierTropy/
  repo-actions: [source, issue]
  downloads: [pdf, epub]
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: ressources-tropy.qmd
      chapters:
      - tropy-officiel.qmd
      - tropy-extensions.qmd
      - tropy-tutos.qmd
      - tropy-videos.qmd
      - tropy-blogs.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: fr
    css: styles.css
    lightbox: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    lang: fr
    documentclass: scrreprt
  epub: 
    epub-cover-image: cover.png
    lang: fr



